gon.term_1 if gon
gon.term_2 if gon
gon.term_3 if gon
gon.term_4 if gon
gon.term_5 if gon
gon.term_6 if gon
gon.term_7 if gon
gon.term_8 if gon
gon.term_9 if gon
gon.term_10 if gon
gon.term_11 if gon
gon.term_12 if gon